# Generated by Django 4.2.7 on 2023-11-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plowing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plowingservice",
            name="name",
            field=models.CharField(default="Plowing Service", max_length=255),
        ),
    ]
