# Generated by Django 4.2.7 on 2023-11-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plowing", "0002_plowingservice_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plowingservice",
            name="name",
            field=models.CharField(default="Plowing Service", max_length=255, unique=True),
        ),
    ]
